# PIPELINE DEFINITION
# Name: addition-pipeline
# Inputs:
#    x: int
#    y: int
# Outputs:
#    Output: int
components:
  comp-add:
    executorLabel: exec-add
    inputDefinitions:
      parameters:
        a:
          parameterType: NUMBER_INTEGER
        b:
          parameterType: NUMBER_INTEGER
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_INTEGER
  comp-add-2:
    executorLabel: exec-add-2
    inputDefinitions:
      parameters:
        a:
          parameterType: NUMBER_INTEGER
        b:
          parameterType: NUMBER_INTEGER
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_INTEGER
deploymentSpec:
  executors:
    exec-add:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - add
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'dotenv' && \"\
          $0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: 10.5.110.131:32000/test-project/my-component:v1
    exec-add-2:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - add
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'dotenv' && \"\
          $0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: 10.5.110.131:32000/test-project/my-component:v1
pipelineInfo:
  name: addition-pipeline
root:
  dag:
    outputs:
      parameters:
        Output:
          valueFromParameter:
            outputParameterKey: Output
            producerSubtask: add-2
    tasks:
      add:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-add
        inputs:
          parameters:
            a:
              componentInputParameter: x
            b:
              componentInputParameter: y
        taskInfo:
          name: add
      add-2:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-add-2
        dependentTasks:
        - add
        inputs:
          parameters:
            a:
              taskOutputParameter:
                outputParameterKey: Output
                producerTask: add
            b:
              componentInputParameter: x
        taskInfo:
          name: add-2
  inputDefinitions:
    parameters:
      x:
        parameterType: NUMBER_INTEGER
      y:
        parameterType: NUMBER_INTEGER
  outputDefinitions:
    parameters:
      Output:
        parameterType: NUMBER_INTEGER
schemaVersion: 2.1.0
sdkVersion: kfp-2.13.0
