[project]
name = "kfp-local"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docker>=7.1.0",
    "kfp>=2.13.0",
    "kfp-kubernetes>=1.5.0",
]
